[package]
name = "p1"
version = "0.1.0"
authors = ["bo <bo@nearprotocol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
default = []
foo = []